### ISSUE TITLE
write ER Diagram of our project.

### ISSUE THREAD

**Issue by xingweitian** [new-airbnb/kitchen#12]
This link may be useful: [ER Diagrams](https://www.lucidchart.com/pages/er-diagrams?a=1)

**Comment by zhangjiangqige** [comment]
This is not very urgent and since our db schema is very likely to change frequently, we can do this in the end of the project.

**Comment by xingweitian** [comment]
Cool, sounds good, I will move it to backlog.

**Comment by zhangjiangqige** [comment]
This can be put in the backlog.

**Comment by xingweitian** [comment]
[ER Diagram Demo](http://ww1.sinaimg.cn/large/005UlHJLly1g1f1vr1uigj30qy0ljn6t.jpg)

@zhangjiangqige @lyuboxin @ericqiangguo Let's talk about it in the next meeting
